// Clinic treatment plan PDF — localized labels (doctor app).

/// Language code: 'en' | 'uz'.
class TreatmentPlanPdfTranslations {
  final String documentTitle;
  final String clinic;
  final String treatmentPlanId;
  final String generatedAt;
  final String planSummarySection;
  final String patientName;
  final String patientId;
  final String planTitle;
  final String diagnosis;
  final String attendingDoctor;
  final String planStatus;
  final String paymentStatus;
  final String planKind;
  final String total;
  final String paid;
  final String outstanding;
  final String created;
  final String updated;
  final String symptoms;
  final String notes;
  final String procedures;
  final String installments;
  final String colIdx;
  final String service;
  final String quantity;
  final String unitPrice;
  final String discount;
  final String lineTotal;
  final String lineStatus;
  final String linkedVisit;
  final String colInstallmentId;
  final String colInstallmentStatus;
  final String colInstallmentAmount;
  final String colNumInstallments;
  final String generatedByShifa;
  final String pageOf;
  final String confidentialDocument;

  /// Per-installment table (within a schedule plan).
  final String colScheduleDueDate;
  final String colScheduleAmount;
  final String colScheduleStatus;

  final String patientSignatureHeading;
  final String patientSignatureNote;
  final String signaturePatientCaption;
  final String signatureDateCaption;

  final String _lang;

  TreatmentPlanPdfTranslations._({
    required this.documentTitle,
    required this.clinic,
    required this.treatmentPlanId,
    required this.generatedAt,
    required this.planSummarySection,
    required this.patientName,
    required this.patientId,
    required this.planTitle,
    required this.diagnosis,
    required this.attendingDoctor,
    required this.planStatus,
    required this.paymentStatus,
    required this.planKind,
    required this.total,
    required this.paid,
    required this.outstanding,
    required this.created,
    required this.updated,
    required this.symptoms,
    required this.notes,
    required this.procedures,
    required this.installments,
    required this.colIdx,
    required this.service,
    required this.quantity,
    required this.unitPrice,
    required this.discount,
    required this.lineTotal,
    required this.lineStatus,
    required this.linkedVisit,
    required this.colInstallmentId,
    required this.colInstallmentStatus,
    required this.colInstallmentAmount,
    required this.colNumInstallments,
    required this.generatedByShifa,
    required this.pageOf,
    required this.confidentialDocument,
    required this.colScheduleDueDate,
    required this.colScheduleAmount,
    required this.colScheduleStatus,
    required this.patientSignatureHeading,
    required this.patientSignatureNote,
    required this.signaturePatientCaption,
    required this.signatureDateCaption,
    required String lang,
  }) : _lang = lang;

  static final Map<String, TreatmentPlanPdfTranslations> _byLocale = {
    'en': TreatmentPlanPdfTranslations._(
      documentTitle: 'Treatment Plan',
      clinic: 'Clinic',
      treatmentPlanId: 'Plan ID',
      generatedAt: 'Generated',
      planSummarySection: 'Plan Summary',
      patientName: 'Patient',
      patientId: 'Patient ID',
      planTitle: 'Title',
      diagnosis: 'Diagnosis',
      attendingDoctor: 'Attending doctor(s)',
      planStatus: 'Plan status',
      paymentStatus: 'Payment status',
      planKind: 'Plan type',
      total: 'Total',
      paid: 'Paid',
      outstanding: 'Outstanding',
      created: 'Created',
      updated: 'Updated',
      symptoms: 'Symptoms / complaints',
      notes: 'Plan notes',
      procedures: 'Procedures & line items',
      installments: 'Installment schedules',
      colIdx: '#',
      service: 'Service',
      quantity: 'Qty',
      unitPrice: 'Unit price',
      discount: 'Discount',
      lineTotal: 'Line total',
      lineStatus: 'Line status',
      linkedVisit: 'Linked visit',
      colInstallmentId: 'Schedule ID',
      colInstallmentStatus: 'Status',
      colInstallmentAmount: 'Scheduled total',
      colNumInstallments: 'Count',
      generatedByShifa:
          'Generated by SHIFA Digital Health Platform · Clinic workspace',
      pageOf: 'Page',
      confidentialDocument:
          'Confidential medical / billing summary · For internal clinic use',
      colScheduleDueDate: 'Due date',
      colScheduleAmount: 'Amount due',
      colScheduleStatus: 'Part status',
      patientSignatureHeading: 'Patient acknowledgement & signature',
      patientSignatureNote:
          'By signing below, I confirm that I have reviewed this treatment plan and '
          'the payment/installment arrangement shown above.',
      signaturePatientCaption: 'Patient signature',
      signatureDateCaption: 'Date',
      lang: 'en',
    ),
    'uz': TreatmentPlanPdfTranslations._(
      documentTitle: 'Davolash rejasi',
      clinic: 'Klinika',
      treatmentPlanId: 'Reja ID',
      generatedAt: 'Chiqarilgan',
      planSummarySection: 'Reja qisqacha',
      patientName: 'Bemor',
      patientId: 'Bemor ID',
      planTitle: 'Nom',
      diagnosis: 'Tashxis',
      attendingDoctor: 'Mas\'ul shifokor(lar)',
      planStatus: 'Reja holati',
      paymentStatus: 'To\'lov holati',
      planKind: 'Reja turi',
      total: 'Jami',
      paid: 'To\'langan',
      outstanding: 'Qoldiq',
      created: 'Yaratilgan',
      updated: 'Yangilangan',
      symptoms: 'Alomatlar / shikoyatlar',
      notes: 'Reja izohlari',
      procedures: 'Tadbirlar va qatorlar',
      installments: 'Bo\'lib-bo\'lib to\'lov jadvallari',
      colIdx: '#',
      service: 'Xizmat',
      quantity: 'Miqdor',
      unitPrice: 'Bir narxi',
      discount: 'Chegirma',
      lineTotal: 'Yig\'indi',
      lineStatus: 'Qator holati',
      linkedVisit: 'Bog\'langan qabul',
      colInstallmentId: 'Jadval ID',
      colInstallmentStatus: 'Holat',
      colInstallmentAmount: 'Rejalashtirilgan jami',
      colNumInstallments: 'Bo\'laklar',
      generatedByShifa:
          'SHIFA raqamli sog\'liqni saqlash platformasi · Klinika',
      pageOf: 'Sahifa',
      confidentialDocument:
          'Maxfiy tibbiy / hisob-kitob hujjati · Klinika uchun',
      colScheduleDueDate: 'Muddati',
      colScheduleAmount: 'Summasi',
      colScheduleStatus: 'Bo\'lak holati',
      patientSignatureHeading: 'Bemor tasdiqi va imzo',
      patientSignatureNote:
          'Pastda imzo chekish orqali ushbu davolash rejasini va yuqorida '
          'ko\'rsatilgan to\'lov / bo\'lib-bo\'lib to\'lash jadvalini '
          'tushunganligim va qabul qilganligimni tasdiqlayman.',
      signaturePatientCaption: 'Bemorning imzosi',
      signatureDateCaption: 'Sana',
      lang: 'uz',
    ),
  };

  static TreatmentPlanPdfTranslations forLanguage(String languageCode) {
    final code = languageCode.toLowerCase().startsWith('uz') ? 'uz' : 'en';
    return _byLocale[code] ?? _byLocale['en']!;
  }

  static List<String> dayNames(String languageCode) {
    final code = languageCode.toLowerCase().startsWith('uz') ? 'uz' : 'en';
    return code == 'uz'
        ? [
            'Dushanba',
            'Seshanba',
            'Chorshanba',
            'Payshanba',
            'Juma',
            'Shanba',
            'Yakshanba',
          ]
        : [
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday',
            'Sunday',
          ];
  }

  static List<String> monthNames(String languageCode) {
    final code = languageCode.toLowerCase().startsWith('uz') ? 'uz' : 'en';
    return code == 'uz'
        ? [
            '',
            'Yanvar',
            'Fevral',
            'Mart',
            'Aprel',
            'May',
            'Iyun',
            'Iyul',
            'Avgust',
            'Sentabr',
            'Oktabr',
            'Noyabr',
            'Dekabr',
          ]
        : [
            '',
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December',
          ];
  }

  String labelPlanStatus(String raw) {
    switch (raw.toUpperCase()) {
      case 'DRAFT':
        return _lbl('Draft', 'Loyiha');
      case 'ACTIVE':
        return _lbl('Active', 'Faol');
      case 'ON_HOLD':
        return _lbl('On hold', 'To\'xtatilgan');
      case 'IN_PROGRESS':
        return _lbl('In progress', 'Jarayonda');
      case 'COMPLETED':
        return _lbl('Completed', 'Yakunlangan');
      case 'CANCELLED':
        return _lbl('Cancelled', 'Bekor qilingan');
      default:
        return raw;
    }
  }

  String labelPaymentStatus(String raw) {
    switch (raw.toUpperCase()) {
      case 'PAID':
        return _lbl('Paid', 'To\'langan');
      case 'PARTIAL':
        return _lbl('Partial', 'Qisman');
      case 'UNPAID':
        return _lbl('Unpaid', 'To\'lanmagan');
      case 'NONE':
      default:
        return raw.isEmpty ? '—' : raw;
    }
  }

  String labelLineStatus(String raw) {
    switch (raw.toUpperCase()) {
      case 'PLANNED':
        return _lbl('Planned', 'Rejalashtirilgan');
      case 'SCHEDULED':
        return _lbl('Scheduled', 'Band qilingan');
      case 'IN_PROGRESS':
        return _lbl('In progress', 'Jarayonda');
      case 'COMPLETED':
        return _lbl('Completed', 'Yakunlangan');
      case 'CANCELLED':
        return _lbl('Cancelled', 'Bekor qilingan');
      default:
        return raw;
    }
  }

  String labelPlanKind(String raw) {
    switch (raw.toUpperCase()) {
      case 'COMPREHENSIVE':
        return _lbl('Comprehensive', 'Kompleks');
      case 'VISIT':
        return _lbl('Visit-based', 'Tashrif asosida');
      default:
        return raw;
    }
  }

  /// Title above the per-duedate installment table for one schedule.
  String installmentScheduleSectionTitle(int installmentPlanId) {
    return _lang == 'uz'
        ? 'Jadval №$installmentPlanId — toʻlov qislari grafigi'
        : 'Schedule #$installmentPlanId — installments by due date';
  }

  String toothSection(String fdi) =>
      _lbl('Tooth $fdi (FDI)', 'Tish $fdi (FDI)');

  String get otherServicesSection =>
      _lbl('Other services', 'Boshqa xizmatlar');

  String labelInstallmentItemStatus(String raw) {
    switch (raw.toUpperCase()) {
      case 'PENDING':
        return _lbl('Pending', 'Kutilmoqda');
      case 'PAID':
        return _lbl('Paid', 'To\'langan');
      case 'OVERDUE':
        return _lbl('Overdue', 'Muddati o\'tgan');
      case 'WAIVED':
        return _lbl('Waived', 'Yechildi');
      case 'CANCELLED':
        return _lbl('Cancelled', 'Bekor qilingan');
      default:
        return raw.isEmpty ? '—' : raw;
    }
  }

  String _lbl(String en, String uz) => _lang == 'uz' ? uz : en;
}
