// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8q7D4Fp1a9rtHzNxTtPdhGlPG-0n56HM',
    appId: '1:55173524197:web:964e0be5d1a5700892420c',
    messagingSenderId: '55173524197',
    projectId: 'shifa-doctor-staging',
    authDomain: 'shifa-doctor-staging.firebaseapp.com',
    storageBucket: 'shifa-doctor-staging.firebasestorage.app',
    measurementId: 'G-W89E3NN4CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONE8lrUzgurI9h0zpw9TqersE-1V5J-8',
    appId: '1:55173524197:android:18af2711f102062d92420c',
    messagingSenderId: '55173524197',
    projectId: 'shifa-doctor-staging',
    storageBucket: 'shifa-doctor-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSXfLL1xIcZVoj0xJZ05n_W81qTEFj6bc',
    appId: '1:55173524197:ios:doctorapp000000092420c',
    messagingSenderId: '55173524197',
    projectId: 'shifa-doctor-staging',
    storageBucket: 'shifa-doctor-staging.firebasestorage.app',
    iosBundleId: 'com.shifa.doctorapp',
  );
}
