// lib/features/appointments/services/appointment_pdf_translations.dart

/// Localized strings for the appointment summary PDF.
/// Language code: 'en' | 'uz'.
class AppointmentPdfTranslations {
  final String appointmentSummary;
  final String patientName;
  final String patientId;
  final String dateOfBirth;
  final String gender;
  final String doctorName;
  final String specialization;
  final String licenseNumber;
  final String appointmentType;
  final String duration;
  final String clinicalNotes;
  final String diagnosis;
  final String prescriptions;
  final String recommendations;
  final String followUpDate;
  final String doctorSignature;
  final String patientSignature;
  final String confidentialMedicalDocument;
  final String generatedByShifa;
  final String pageOf;
  final String watermarkText;
  final String appointmentIdLabel;
  final String videoConsultation;
  final String faceToFace;
  final String beforeTreatment;
  final String afterTreatment;
  final String imageLabel;
  final String signedElectronicallyOn;
  final String viaShifaPatientApp;

  /// Section headers / dental billing columns
  final String clinic;
  final String signaturesSection;
  final String servicesProvided;
  final String toothColumn;
  final String serviceColumn;
  final String amountColumn;
  final String subtotalRow;
  final String discountRow;
  final String totalRow;

  final String treatmentPlanSection;
  final String treatmentPlanTitle;
  final String planTotalRow;
  final String planPaidRow;
  final String planOutstandingRow;
  final String fulfilledThisVisit;
  final String sessionPaymentRow;

  const AppointmentPdfTranslations({
    required this.appointmentSummary,
    required this.patientName,
    required this.patientId,
    required this.dateOfBirth,
    required this.gender,
    required this.doctorName,
    required this.specialization,
    required this.licenseNumber,
    required this.appointmentType,
    required this.duration,
    required this.clinicalNotes,
    required this.diagnosis,
    required this.prescriptions,
    required this.recommendations,
    required this.followUpDate,
    required this.doctorSignature,
    required this.patientSignature,
    required this.confidentialMedicalDocument,
    required this.generatedByShifa,
    required this.pageOf,
    required this.watermarkText,
    required this.appointmentIdLabel,
    required this.videoConsultation,
    required this.faceToFace,
    required this.beforeTreatment,
    required this.afterTreatment,
    required this.imageLabel,
    required this.signedElectronicallyOn,
    required this.viaShifaPatientApp,
    required this.clinic,
    required this.signaturesSection,
    required this.servicesProvided,
    required this.toothColumn,
    required this.serviceColumn,
    required this.amountColumn,
    required this.subtotalRow,
    required this.discountRow,
    required this.totalRow,
    required this.treatmentPlanSection,
    required this.treatmentPlanTitle,
    required this.planTotalRow,
    required this.planPaidRow,
    required this.planOutstandingRow,
    required this.fulfilledThisVisit,
    required this.sessionPaymentRow,
  });

  static const Map<String, AppointmentPdfTranslations> _byLocale = {
    'en': AppointmentPdfTranslations(
      appointmentSummary: 'Appointment Summary',
      patientName: 'Patient Name',
      patientId: 'Patient ID',
      dateOfBirth: 'Date of Birth',
      gender: 'Gender',
      doctorName: 'Doctor Name',
      specialization: 'Specialization',
      licenseNumber: 'License Number',
      appointmentType: 'Appointment Type',
      duration: 'Duration',
      clinicalNotes: 'Clinical Notes',
      diagnosis: 'Diagnosis',
      prescriptions: 'Prescriptions',
      recommendations: 'Recommendations',
      followUpDate: 'Follow-up Date',
      doctorSignature: 'Doctor Signature',
      patientSignature: 'Patient Signature',
      confidentialMedicalDocument: 'Confidential Medical Document',
      generatedByShifa: 'Generated by SHIFA Digital Health Platform',
      pageOf: 'Page',
      watermarkText: 'SHIFA MEDICAL REPORT',
      appointmentIdLabel: 'Appointment ID',
      videoConsultation: 'Video',
      faceToFace: 'Face-to-face',
      beforeTreatment: 'Before Treatment',
      afterTreatment: 'After Treatment',
      imageLabel: 'Image',
      signedElectronicallyOn: 'Signed electronically on',
      viaShifaPatientApp: 'via SHIFA Patient App',
      clinic: 'Clinic',
      signaturesSection: 'Signatures',
      servicesProvided: 'Services provided',
      toothColumn: 'Tooth',
      serviceColumn: 'Service',
      amountColumn: 'Amount',
      subtotalRow: 'Subtotal',
      discountRow: 'Discount',
      totalRow: 'Total payment',
      treatmentPlanSection: 'Treatment plan',
      treatmentPlanTitle: 'Plan',
      planTotalRow: 'Plan total',
      planPaidRow: 'Paid',
      planOutstandingRow: 'Outstanding',
      fulfilledThisVisit: 'Completed this visit',
      sessionPaymentRow: 'Payment this visit',
    ),
    'uz': AppointmentPdfTranslations(
      appointmentSummary: 'Qabul Xulosasi',
      patientName: 'Bemor Ismi',
      patientId: 'Bemor ID',
      dateOfBirth: 'Tug\'ilgan sana',
      gender: 'Jins',
      doctorName: 'Shifokor Ismi',
      specialization: 'Mutaxassislik',
      licenseNumber: 'Litsenziya raqami',
      appointmentType: 'Qabul Turi',
      duration: 'Davomiylik',
      clinicalNotes: 'Klinik Izohlar',
      diagnosis: 'Tashxis',
      prescriptions: 'Retseptlar',
      recommendations: 'Tavsiyalar',
      followUpDate: 'Keyingi qabul sanasi',
      doctorSignature: 'Shifokor Imzosi',
      patientSignature: 'Bemor Imzosi',
      confidentialMedicalDocument: 'Maxfiy Tibbiy Hujjat',
      generatedByShifa: 'SHIFA Raqamli Sog\'liqni Saqlash Platformasi tomonidan yaratilgan',
      pageOf: 'Sahifa',
      watermarkText: 'SHIFA TIBBIY HISOBOT',
      appointmentIdLabel: 'Qabul ID',
      videoConsultation: 'Video',
      faceToFace: 'Shaxsan',
      beforeTreatment: 'Davolashdan oldin',
      afterTreatment: 'Davolashdan keyin',
      imageLabel: 'Rasm',
      signedElectronicallyOn: 'Elektron imzo sanasi',
      viaShifaPatientApp: 'SHIFA Bemor ilovasi orqali',
      clinic: 'Klinika',
      signaturesSection: 'Imzolar',
      servicesProvided: 'Ko\'rsatilgan xizmatlar',
      toothColumn: 'Tish',
      serviceColumn: 'Xizmat',
      amountColumn: 'Summa',
      subtotalRow: 'Oraliq jami',
      discountRow: 'Chegirma',
      totalRow: 'To\'lov',
      treatmentPlanSection: 'Davolash rejasi',
      treatmentPlanTitle: 'Reja',
      planTotalRow: 'Reja jami',
      planPaidRow: 'To\'langan',
      planOutstandingRow: 'Qoldiq',
      fulfilledThisVisit: 'Ushbu qabulda bajarildi',
      sessionPaymentRow: 'Ushbu qabulda to\'langan pul miqdori',
    ),
  };

  static AppointmentPdfTranslations forLanguage(String languageCode) {
    final code = languageCode.toLowerCase().startsWith('uz') ? 'uz' : 'en';
    return _byLocale[code] ?? _byLocale['en']!;
  }

  /// Day names for header. DateTime.weekday 1=Mon..7=Sun; use dayNames()[date.weekday - 1].
  static List<String> dayNames(String languageCode) {
    final code = languageCode.toLowerCase().startsWith('uz') ? 'uz' : 'en';
    return code == 'uz'
        ? ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba', 'Yakshanba']
        : ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  }

  /// Month names (1-based index).
  static List<String> monthNames(String languageCode) {
    final code = languageCode.toLowerCase().startsWith('uz') ? 'uz' : 'en';
    return code == 'uz'
        ? ['', 'Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr']
        : ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  }
}
